version: '3.9'

x-base_service: &base_service
  ports:
    - "${WEBUI_PORT:-7860}:7860"
  volumes:
    - &v1 ./data:/data
    - &v2 ./output:/output
  stop_signal: SIGKILL
  tty: true
  networks:
    - mynetwork
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [compute, utility]

name: webui-docker

networks:
  mynetwork:
    driver: bridge

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto", "combined"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:72
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  auto-cpu:
    <<: *automatic
    profiles: ["auto-cpu", "combined-cpu"]
    deploy: {}
    environment:
      - CLI_ARGS=--no-half --precision full --allow-code --enable-insecure-extension-access --api

  relay-node:
    networks:
      - mynetwork
    ports:
      - "${RELAY_NODE_PORT:-6387}:6387"
    profiles: ["relay-node", "combined", "combined-cpu"]
    build:
      context: ./services/relay-node
      args:
        - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
    environment:
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
      - SD_URL=${SD_URL:-http://auto:7860}
